# Generated by Django 6.0 on 2025-12-20 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('city', models.CharField(max_length=100, verbose_name='Shahar')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('event_date', models.DateTimeField(verbose_name='Tadbir vaqti')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr etilgan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='Holati')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Rasm')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='events/qr_codes/', verbose_name='QR kod')),
                ('share_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ulashish URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Huquq berilgan vaqti')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='events.event', verbose_name='Tadbir')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_event_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Huquq bergan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tadbirga kirish huquqi',
                'verbose_name_plural': 'Tadbirga kirish huquqlari',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['city', 'event_date'], name='events_even_city_4dc7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'event_date'], name='events_even_status_fcd052_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventaccess',
            unique_together={('user', 'event')},
        ),
    ]
