# Generated by Django 6.0 on 2025-12-20 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='eventaccess',
            options={'verbose_name': 'Доступ к событию', 'verbose_name_plural': 'Доступы к событиям'},
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name='Время события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='events/qr_codes/', verbose_name='QR код'),
        ),
        migrations.AlterField(
            model_name='event',
            name='share_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL для шаринга'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='eventaccess',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='events.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='eventaccess',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время предоставления доступа'),
        ),
        migrations.AlterField(
            model_name='eventaccess',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_event_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Предоставил доступ'),
        ),
        migrations.AlterField(
            model_name='eventaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
