# Generated by Django 6.0 on 2025-12-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_upcomingevent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_city_4dc7bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_status_fcd052_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='EventAccess',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
