# Generated by Django 6.0 on 2025-12-20 11:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqami')),
                ('role', models.CharField(choices=[('designer', "Dizayner/Me'mor"), ('repair', "Ta'mirlash guruhi/Pudratchi"), ('supplier', "Yetkazib beruvchi/Ko'rgazma zali/Fabrik"), ('media', 'Interior Design Magazine / Media'), ('admin', 'Administrator')], max_length=20, verbose_name='Foydalanuvchi roli')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Telefon tasdiqlangan')),
                ('is_profile_completed', models.BooleanField(default=False, verbose_name="Profil to'ldirilgan")),
                ('is_active_profile', models.BooleanField(default=False, verbose_name="Profil faol (moderatsiyadan o'tgan)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="To'liq ism")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Fotosurat')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Veb-sayt')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('vk', models.CharField(blank=True, max_length=100, null=True, verbose_name='VKontakte')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kompaniya nomi')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='INN')),
                ('product_categories', models.JSONField(blank=True, default=list, verbose_name='Mahsulot kategoriyalari')),
                ('brands', models.JSONField(blank=True, default=list, verbose_name='Brendlar')),
                ('team_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jamoa nomi')),
                ('work_types', models.JSONField(blank=True, default=list, verbose_name='Ish turlari')),
                ('cooperation_terms', models.TextField(blank=True, null=True, verbose_name='Hamkorlik shartlari')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='users/qr_codes/', verbose_name='QR kod')),
                ('share_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ulashish URL')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SMSVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('code', models.CharField(max_length=6, verbose_name='Kod')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('expires_at', models.DateTimeField(verbose_name='Muddati tugaydi')),
            ],
            options={
                'verbose_name': 'SMS tasdiqlash kodi',
                'verbose_name_plural': 'SMS tasdiqlash kodlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'code', 'is_used'], name='accounts_sm_phone_004273_idx')],
            },
        ),
    ]
