# Generated by Django 6.0 on 2025-12-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active_profile',
            field=models.BooleanField(default=False, verbose_name='Профиль активен (прошел модерацию)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Телефон подтвержден'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_profile_completed',
            field=models.BooleanField(default=False, verbose_name='Профиль заполнен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('designer', 'Дизайнер/Архитектор'), ('repair', 'Ремонтная группа/Подрядчик'), ('supplier', 'Поставщик/Выставочный зал/Фабрика'), ('media', 'Журнал по дизайну интерьера / Медиа'), ('admin', 'Администратор')], max_length=20, verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
