# Generated by Django 6.0 on 2025-12-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsverificationcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'SMS код подтверждения', 'verbose_name_plural': 'SMS коды подтверждения'},
        ),
        migrations.AlterField(
            model_name='smsverificationcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='smsverificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='smsverificationcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Срок действия'),
        ),
        migrations.AlterField(
            model_name='smsverificationcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='smsverificationcode',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='brands',
            field=models.JSONField(blank=True, default=list, verbose_name='Бренды'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cooperation_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Условия сотрудничества'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='product_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='Категории товаров'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='users/qr_codes/', verbose_name='QR код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='share_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL для шаринга'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Веб-сайт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Виды работ'),
        ),
    ]
