# Generated by Django 6.0 on 2025-12-23 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_smsverificationcode_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('full_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИ на английском')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('city', models.CharField(max_length=100, verbose_name='Город проживания')),
                ('services', models.JSONField(default=list, verbose_name='Услуги')),
                ('work_type', models.CharField(blank=True, choices=[('own_name', 'Под собственным именем'), ('studio', 'В студии')], max_length=20, null=True, verbose_name='Тип работы')),
                ('welcome_message', models.TextField(blank=True, null=True, verbose_name='Приветственное сообщение о вас и вашем опыте')),
                ('work_cities', models.JSONField(blank=True, default=list, verbose_name='Города работы')),
                ('cooperation_terms', models.TextField(blank=True, null=True, verbose_name='Условия сотрудничества при работе с объектами в других городах или регионах')),
                ('segments', models.JSONField(blank=True, default=list, verbose_name='Сегменты работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Анкета дизайнера',
                'verbose_name_plural': 'Анкеты дизайнеров',
                'ordering': ['-created_at'],
            },
        ),
    ]
