# Generated by Django 6.0 on 2025-12-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_designerquestionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designerquestionnaire',
            name='user',
        ),
    ]
