# Generated by Django 6.0 on 2025-12-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_repairquestionnaire_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerquestionnaire',
            name='group',
            field=models.CharField(default='Дизайнер / Архитектор и тд', max_length=255, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='repairquestionnaire',
            name='group',
            field=models.CharField(default='Ремонтная бригада / Подрядчик', max_length=255, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='repairquestionnaire',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
    ]
