# Generated by Django 6.0 on 2025-12-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_designerquestionnaire_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerquestionnaire',
            name='group',
            field=models.CharField(choices=[('designer', 'Дизайнер / Архитектор и тд')], default='designer', max_length=50, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='repairquestionnaire',
            name='group',
            field=models.CharField(choices=[('repair', 'Ремонтная бригада / Подрядчик')], default='repair', max_length=50, verbose_name='Группа'),
        ),
    ]
