# Generated by Django 6.0 on 2025-12-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_designerquestionnaire_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerquestionnaire',
            name='group',
            field=models.CharField(choices=[('designer', 'Дизайнер'), ('architect', 'Архитектор'), ('decorator', 'Декоратор'), ('landscape_designer', 'Ландшафтный дизайнер'), ('light_designer', 'Светодизайнер'), ('interior_designer', 'Дизайнер интерьера'), ('repair_team', 'Ремонтная бригада'), ('contractor', 'Подрядчик'), ('supplier', 'Поставщик'), ('exhibition_hall', 'Выставочный зал'), ('factory', 'Фабрика')], default='designer', max_length=50, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='repairquestionnaire',
            name='group',
            field=models.CharField(choices=[('designer', 'Дизайнер'), ('architect', 'Архитектор'), ('decorator', 'Декоратор'), ('landscape_designer', 'Ландшафтный дизайнер'), ('light_designer', 'Светодизайнер'), ('interior_designer', 'Дизайнер интерьера'), ('repair_team', 'Ремонтная бригада'), ('contractor', 'Подрядчик'), ('supplier', 'Поставщик'), ('exhibition_hall', 'Выставочный зал'), ('factory', 'Фабрика')], default='repair', max_length=50, verbose_name='Группа'),
        ),
    ]
