# Generated by Django 6.0 on 2025-12-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_designerquestionnaire_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerquestionnaire',
            name='group',
            field=models.CharField(choices=[('designer', 'Дизайнер'), ('architect', 'Архитектор'), ('repair_team', 'Ремонтная бригада'), ('contractor', 'Подрядчик'), ('supplier', 'Поставщик'), ('factory', 'Фабрика'), ('salon', 'Салон')], default='designer', max_length=50, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='repairquestionnaire',
            name='group',
            field=models.CharField(choices=[('designer', 'Дизайнер'), ('architect', 'Архитектор'), ('repair_team', 'Ремонтная бригада'), ('contractor', 'Подрядчик'), ('supplier', 'Поставщик'), ('factory', 'Фабрика'), ('salon', 'Салон')], default='repair_team', max_length=50, verbose_name='Группа'),
        ),
    ]
