# Generated by Django 6.0 on 2025-12-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_designerquestionnaire_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerquestionnaire',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('archived', 'В архиве')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='repairquestionnaire',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('archived', 'В архиве')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
