# Generated by Django 6.0 on 2025-12-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_designerquestionnaire_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('designer', 'Дизайнер'), ('architect', 'Архитектор'), ('repair_team', 'Ремонтная бригада'), ('contractor', 'Подрядчик'), ('supplier', 'Поставщик'), ('factory', 'Фабрика'), ('salon', 'Салон')], default='supplier', max_length=50, verbose_name='Группа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('archived', 'В архиве')], default='pending', max_length=20, verbose_name='Статус')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('brand_name', models.CharField(max_length=255, verbose_name='Название бренда (дополнительно в скобках укажите полное юридическое наименование компании)')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('responsible_person', models.TextField(verbose_name='Имя, должность и контактный номер ответственного лица')),
                ('representative_cities', models.JSONField(blank=True, default=list, verbose_name='Города представительств или салонов')),
                ('business_form', models.CharField(blank=True, choices=[('own_business', 'Собственный бизнес'), ('franchise', 'Франшиза')], max_length=20, null=True, verbose_name='Форма бизнеса')),
                ('product_assortment', models.TextField(blank=True, null=True, verbose_name='Ассортимент продукции')),
                ('welcome_message', models.TextField(blank=True, null=True, verbose_name='Приветственное сообщение о вашей компании')),
                ('cooperation_terms', models.TextField(blank=True, null=True, verbose_name='Условия сотрудничества при работе с клиентами из других городов или регионов')),
                ('segments', models.JSONField(blank=True, default=list, verbose_name='Сегменты работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Анкета поставщика / салона / фабрики',
                'verbose_name_plural': 'Анкеты поставщиков / салонов / фабрик',
                'ordering': ['-created_at'],
            },
        ),
    ]
