# Generated by Django 6.0 on 2025-12-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_supplierquestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/logos/', verbose_name='Логотип компании (shaxsiy kabinet uchun)'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='data_processing_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку данных'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='delivery_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Сроки поставки и формат работы'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='designer_contractor_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Условия работы с дизайнерами и/или подрядчиками'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='guarantees',
            field=models.TextField(blank=True, null=True, verbose_name='Гарантии и их сроки'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='legal_entity_card',
            field=models.FileField(blank=True, null=True, upload_to='suppliers/legal_cards/', verbose_name='Yuridik shaxs kartasi (shartnoma uchun)'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='magazine_cards',
            field=models.CharField(blank=True, choices=[('hi_home', 'Hi Home'), ('in_home', 'IN HOME'), ('no', 'Нет'), ('other', 'Другое')], max_length=20, null=True, verbose_name='Выдаёте ли вы карточки журналов при покупке продукции?'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='other_contacts',
            field=models.JSONField(blank=True, default=list, verbose_name='Другое (Boshqa) - дополнительные контакты'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='pinterest',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pinterest'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='telegram_channel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram kanal'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='vat_payment',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], max_length=10, null=True, verbose_name='Возможна ли оплата с учётом НДС?'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='vk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VK'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Ваш сайт (Veb-sayt)'),
        ),
    ]
