# Generated by Django 6.0 on 2025-12-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_supplierquestionnaire_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerquestionnaire',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='designerquestionnaire',
            name='data_processing_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку данных'),
        ),
        migrations.AddField(
            model_name='designerquestionnaire',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='designerquestionnaire',
            name='other_contacts',
            field=models.JSONField(blank=True, default=list, verbose_name='Другое - дополнительные контакты'),
        ),
        migrations.AddField(
            model_name='designerquestionnaire',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='designers/photos/', verbose_name='Прикрепите ваше фото для личного кабинета'),
        ),
        migrations.AddField(
            model_name='designerquestionnaire',
            name='pinterest',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pinterest'),
        ),
        migrations.AddField(
            model_name='designerquestionnaire',
            name='service_packages_description',
            field=models.TextField(blank=True, null=True, verbose_name='Подробное описание пакетов услуг с указанием стоимости'),
        ),
        migrations.AddField(
            model_name='designerquestionnaire',
            name='supplier_contractor_recommendation_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Условия сотрудничества по рекомендациям от поставщиков или подрядчиков'),
        ),
        migrations.AddField(
            model_name='designerquestionnaire',
            name='telegram_channel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram канал'),
        ),
        migrations.AddField(
            model_name='designerquestionnaire',
            name='unique_trade_proposal',
            field=models.TextField(blank=True, null=True, verbose_name='Ваше уникальное торговое предложение (УТП)'),
        ),
        migrations.AddField(
            model_name='designerquestionnaire',
            name='vat_payment',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], max_length=10, null=True, verbose_name='Возможна ли оплата с учётом НДС?'),
        ),
        migrations.AddField(
            model_name='designerquestionnaire',
            name='vk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VK'),
        ),
        migrations.AddField(
            model_name='designerquestionnaire',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Ваш сайт'),
        ),
    ]
