# Generated by Django 6.0 on 2025-12-25 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_mediaquestionnaire_repairquestionnaire_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerquestionnaire',
            name='group',
            field=models.CharField(choices=[('supplier', 'Поставщик'), ('repair', 'Ремонт'), ('design', 'Дизайн'), ('media', 'Медиа')], default='designer', max_length=50, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='mediaquestionnaire',
            name='group',
            field=models.CharField(choices=[('supplier', 'Поставщик'), ('repair', 'Ремонт'), ('design', 'Дизайн'), ('media', 'Медиа')], default='supplier', max_length=50, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='repairquestionnaire',
            name='group',
            field=models.CharField(choices=[('supplier', 'Поставщик'), ('repair', 'Ремонт'), ('design', 'Дизайн'), ('media', 'Медиа')], default='repair_team', max_length=50, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='supplierquestionnaire',
            name='group',
            field=models.CharField(choices=[('supplier', 'Поставщик'), ('repair', 'Ремонт'), ('design', 'Дизайн'), ('media', 'Медиа')], default='supplier', max_length=50, verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='QuestionnaireRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Поставщик', 'Поставщик'), ('Ремонт', 'Ремонт'), ('Дизайн', 'Дизайн'), ('Медиа', 'Медиа')], max_length=20, verbose_name='Роль (модель)')),
                ('questionnaire_id', models.IntegerField(verbose_name='ID анкеты')),
                ('is_positive', models.BooleanField(default=True, verbose_name='Положительный отзыв (⭐)')),
                ('is_constructive', models.BooleanField(default=False, verbose_name='Конструктивный отзыв (☆)')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Оставивший отзыв')),
            ],
            options={
                'verbose_name': 'Рейтинг анкеты',
                'verbose_name_plural': 'Рейтинги анкет',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role', 'questionnaire_id', 'status'], name='accounts_qu_role_b46213_idx'), models.Index(fields=['reviewer', 'role', 'questionnaire_id'], name='accounts_qu_reviewe_ce821a_idx')],
                'constraints': [models.UniqueConstraint(fields=('reviewer', 'role', 'questionnaire_id'), name='unique_rating_per_questionnaire')],
            },
        ),
    ]
