# Generated by Django 6.0 on 2025-12-25 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_designerquestionnaire_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='events/posters/', verbose_name='Афиша')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('event_type', models.CharField(choices=[('training', 'ОБУЧЕНИЕ'), ('presentation', 'ПРЕЗЕНТАЦИЯ'), ('opening', 'ОТКРЫТИЕ'), ('leisure', 'ДОСУГОВО-РАЗВЛЕКАТЕЛЬНАЯ')], max_length=50, verbose_name='Тип мероприятия')),
                ('announcement', models.TextField(verbose_name='Анонс мероприятия')),
                ('event_date', models.DateTimeField(verbose_name='Дата и время проведения мероприятия')),
                ('event_location', models.TextField(verbose_name='Место проведения мероприятия')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('registration_phone', models.CharField(max_length=20, verbose_name='Телефон для записи')),
                ('about_event', models.TextField(verbose_name='О мероприятии')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Ближайшее мероприятие',
                'verbose_name_plural': 'Ближайшие мероприятия',
                'ordering': ['event_date'],
                'indexes': [models.Index(fields=['city', 'event_date'], name='accounts_up_city_c184c1_idx'), models.Index(fields=['status', 'event_date'], name='accounts_up_status_39fdab_idx'), models.Index(fields=['event_type', 'event_date'], name='accounts_up_event_t_578221_idx')],
            },
        ),
    ]
