# Generated by Django 6.0 on 2025-12-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_upcomingevent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='upcomingevent',
            name='accounts_up_city_c184c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='upcomingevent',
            name='accounts_up_status_39fdab_idx',
        ),
        migrations.RemoveIndex(
            model_name='upcomingevent',
            name='accounts_up_event_t_578221_idx',
        ),
        migrations.DeleteModel(
            name='UpcomingEvent',
        ),
    ]
