# Generated by Django 6.0 on 2025-12-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_upcomingevent_accounts_up_city_c184c1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='questionnairerating',
            name='accounts_qu_role_b46213_idx',
        ),
        migrations.RemoveIndex(
            model_name='questionnairerating',
            name='accounts_qu_reviewe_ce821a_idx',
        ),
        migrations.RemoveConstraint(
            model_name='questionnairerating',
            name='unique_rating_per_questionnaire',
        ),
        migrations.DeleteModel(
            name='QuestionnaireRating',
        ),
    ]
