# Generated by Django 6.0 on 2025-12-26 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_questionnairerating_accounts_qu_role_b46213_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerquestionnaire',
            name='is_moderation',
            field=models.BooleanField(default=False, verbose_name='Модерация пройдена'),
        ),
        migrations.AddField(
            model_name='mediaquestionnaire',
            name='is_moderation',
            field=models.BooleanField(default=False, verbose_name='Модерация пройдена'),
        ),
        migrations.AddField(
            model_name='repairquestionnaire',
            name='is_moderation',
            field=models.BooleanField(default=False, verbose_name='Модерация пройдена'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='is_moderation',
            field=models.BooleanField(default=False, verbose_name='Модерация пройдена'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'start_date', 'end_date'], name='accounts_re_user_id_0dfec7_idx')],
            },
        ),
    ]
