# Generated by Django 6.0 on 2025-12-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_designerquestionnaire_is_moderation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerquestionnaire',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
