# Generated by Django 6.0 on 2025-12-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_designerquestionnaire_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaquestionnaire',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
