# Generated by Django 6.0 on 2026-01-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_repairquestionnaire_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaquestionnaire',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='repairquestionnaire',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
