# Generated by Django 5.2.6 on 2026-01-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_mediaquestionnaire_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repairquestionnaire',
            name='legal_entity_card',
        ),
        migrations.RemoveField(
            model_name='supplierquestionnaire',
            name='legal_entity_card',
        ),
        migrations.AddField(
            model_name='mediaquestionnaire',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logos/', verbose_name='Логотип компании (shaxsiy kabinet uchun)'),
        ),
    ]
