# Generated by Django 5.2.6 on 2026-01-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_add_company_logo_to_media_questionnaire'),
    ]

    operations = [
        # RepairQuestionnaire uchun - SQL orqali to'g'ridan-to'g'ri o'zgartirish
        migrations.RunSQL(
            # Forward migration
            sql=[
                # Temporary column yaratish
                "ALTER TABLE accounts_repairquestionnaire ADD COLUMN magazine_cards_temp TEXT;",
                # Ma'lumotlarni ko'chirish
                "UPDATE accounts_repairquestionnaire SET magazine_cards_temp = magazine_cards;",
                # Field'ni o'zgartirish (CharField -> JSONField)
                "ALTER TABLE accounts_repairquestionnaire ALTER COLUMN magazine_cards TYPE jsonb USING CASE WHEN magazine_cards_temp IS NULL OR magazine_cards_temp = '' THEN '[]'::jsonb ELSE jsonb_build_array(magazine_cards_temp) END;",
                # Temporary column'ni o'chirish
                "ALTER TABLE accounts_repairquestionnaire DROP COLUMN magazine_cards_temp;",
            ],
            # Reverse migration
            reverse_sql=[
                # Temporary column yaratish
                "ALTER TABLE accounts_repairquestionnaire ADD COLUMN magazine_cards_temp TEXT;",
                # JSON'dan string'ga o'zgartirish
                "UPDATE accounts_repairquestionnaire SET magazine_cards_temp = CASE WHEN jsonb_typeof(magazine_cards) = 'array' AND jsonb_array_length(magazine_cards) > 0 THEN magazine_cards->>0 ELSE NULL END;",
                # Field'ni o'zgartirish (JSONField -> CharField)
                "ALTER TABLE accounts_repairquestionnaire ALTER COLUMN magazine_cards TYPE varchar(20) USING magazine_cards_temp;",
                # Temporary column'ni o'chirish
                "ALTER TABLE accounts_repairquestionnaire DROP COLUMN magazine_cards_temp;",
            ],
        ),
        # SupplierQuestionnaire uchun - SQL orqali to'g'ridan-to'g'ri o'zgartirish
        migrations.RunSQL(
            # Forward migration
            sql=[
                # Temporary column yaratish
                "ALTER TABLE accounts_supplierquestionnaire ADD COLUMN magazine_cards_temp TEXT;",
                # Ma'lumotlarni ko'chirish
                "UPDATE accounts_supplierquestionnaire SET magazine_cards_temp = magazine_cards;",
                # Field'ni o'zgartirish (CharField -> JSONField)
                "ALTER TABLE accounts_supplierquestionnaire ALTER COLUMN magazine_cards TYPE jsonb USING CASE WHEN magazine_cards_temp IS NULL OR magazine_cards_temp = '' THEN '[]'::jsonb ELSE jsonb_build_array(magazine_cards_temp) END;",
                # Temporary column'ni o'chirish
                "ALTER TABLE accounts_supplierquestionnaire DROP COLUMN magazine_cards_temp;",
            ],
            # Reverse migration
            reverse_sql=[
                # Temporary column yaratish
                "ALTER TABLE accounts_supplierquestionnaire ADD COLUMN magazine_cards_temp TEXT;",
                # JSON'dan string'ga o'zgartirish
                "UPDATE accounts_supplierquestionnaire SET magazine_cards_temp = CASE WHEN jsonb_typeof(magazine_cards) = 'array' AND jsonb_array_length(magazine_cards) > 0 THEN magazine_cards->>0 ELSE NULL END;",
                # Field'ni o'zgartirish (JSONField -> CharField)
                "ALTER TABLE accounts_supplierquestionnaire ALTER COLUMN magazine_cards TYPE varchar(20) USING magazine_cards_temp;",
                # Temporary column'ni o'chirish
                "ALTER TABLE accounts_supplierquestionnaire DROP COLUMN magazine_cards_temp;",
            ],
        ),
        # Django state'ni yangilash (migration state uchun)
        migrations.AlterField(
            model_name='repairquestionnaire',
            name='magazine_cards',
            field=models.JSONField(blank=True, default=list, verbose_name='Выдаёте ли вы карточки журналов при рекомендации при заключении договора?'),
        ),
        migrations.AlterField(
            model_name='supplierquestionnaire',
            name='magazine_cards',
            field=models.JSONField(blank=True, default=list, verbose_name='Выдаёте ли вы карточки журналов при покупке продукции?'),
        ),
    ]
