# Generated by Django
# delivery_terms va speed_of_execution ni JSONField ga o'zgartirish

from django.db import migrations, models


def convert_supplier_fields(apps, schema_editor):
    """SupplierQuestionnaire: delivery_terms (text->list), speed_of_execution (char->list) -> _new columns"""
    SupplierQuestionnaire = apps.get_model('accounts', 'SupplierQuestionnaire')
    for obj in SupplierQuestionnaire.objects.all():
        updates = {}
        v = getattr(obj, 'delivery_terms', None)
        updates['delivery_terms_new'] = [v] if v and str(v).strip() else []
        v = getattr(obj, 'speed_of_execution', None)
        updates['speed_of_execution_new'] = [v] if v and str(v).strip() else []
        SupplierQuestionnaire.objects.filter(pk=obj.pk).update(**updates)


def convert_repair_speed(apps, schema_editor):
    """RepairQuestionnaire: speed_of_execution (char->list) -> _new column"""
    RepairQuestionnaire = apps.get_model('accounts', 'RepairQuestionnaire')
    for obj in RepairQuestionnaire.objects.all():
        v = getattr(obj, 'speed_of_execution', None)
        new_val = [v] if v and str(v).strip() else []
        RepairQuestionnaire.objects.filter(pk=obj.pk).update(speed_of_execution_new=new_val)


def reverse_supplier(apps, schema_editor):
    """Reverse: not used - we remove old fields before rename, reverse would need old columns"""
    pass


def reverse_repair(apps, schema_editor):
    """Reverse: not used"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_supplier_questionnaire_secondary_filter_fields'),
    ]

    operations = [
        # 1. Add new JSONField columns (temporary names)
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='delivery_terms_new',
            field=models.JSONField(blank=True, default=list, verbose_name='Сроки поставки и формат работы'),
        ),
        migrations.AddField(
            model_name='supplierquestionnaire',
            name='speed_of_execution_new',
            field=models.JSONField(blank=True, default=list, verbose_name='Скорость исполнения'),
        ),
        migrations.AddField(
            model_name='repairquestionnaire',
            name='speed_of_execution_new',
            field=models.JSONField(blank=True, default=list, verbose_name='Скорость исполнения'),
        ),
        # 2. Data migration
        migrations.RunPython(convert_supplier_fields, reverse_supplier),
        migrations.RunPython(convert_repair_speed, reverse_repair),
        # 3. Remove old, rename new
        migrations.RemoveField(model_name='supplierquestionnaire', name='delivery_terms'),
        migrations.RemoveField(model_name='supplierquestionnaire', name='speed_of_execution'),
        migrations.RemoveField(model_name='repairquestionnaire', name='speed_of_execution'),
        migrations.RenameField(
            model_name='supplierquestionnaire',
            old_name='delivery_terms_new',
            new_name='delivery_terms',
        ),
        migrations.RenameField(
            model_name='supplierquestionnaire',
            old_name='speed_of_execution_new',
            new_name='speed_of_execution',
        ),
        migrations.RenameField(
            model_name='repairquestionnaire',
            old_name='speed_of_execution_new',
            new_name='speed_of_execution',
        ),
    ]
