# Generated by Django 6.0 on 2025-12-20 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Jami sharhlar soni')),
                ('positive_reviews', models.IntegerField(default=0, verbose_name='Ijobiy sharhlar soni')),
                ('negative_reviews', models.IntegerField(default=0, verbose_name='Salbiy sharhlar soni')),
                ('stars', models.IntegerField(default=0, verbose_name='Yulduzcha reytingi')),
                ('positive_ratio', models.FloatField(default=0.0, verbose_name='Ijobiy sharhlar nisbati')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi reytingi',
                'verbose_name_plural': 'Foydalanuvchi reytinglari',
                'ordering': ['-stars', '-positive_ratio'],
            },
        ),
    ]
