# Generated by Django 6.0 on 2025-12-20 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrating',
            options={'ordering': ['-stars', '-positive_ratio'], 'verbose_name': 'Рейтинг пользователя', 'verbose_name_plural': 'Рейтинги пользователей'},
        ),
        migrations.AlterField(
            model_name='userrating',
            name='negative_reviews',
            field=models.IntegerField(default=0, verbose_name='Отрицательных отзывов'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='positive_ratio',
            field=models.FloatField(default=0.0, verbose_name='Доля положительных отзывов'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='positive_reviews',
            field=models.IntegerField(default=0, verbose_name='Положительных отзывов'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='stars',
            field=models.IntegerField(default=0, verbose_name='Звездный рейтинг'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='total_reviews',
            field=models.IntegerField(default=0, verbose_name='Всего отзывов'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
