# Generated by Django 6.0 on 2025-12-26 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_userrating_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Поставщик', 'Поставщик'), ('Ремонт', 'Ремонт'), ('Дизайн', 'Дизайн'), ('Медиа', 'Медиа')], max_length=20, verbose_name='Роль (модель)')),
                ('questionnaire_id', models.IntegerField(verbose_name='ID анкеты')),
                ('is_positive', models.BooleanField(default=True, verbose_name='Положительный отзыв (⭐)')),
                ('is_constructive', models.BooleanField(default=False, verbose_name='Конструктивный отзыв (☆)')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Оставивший отзыв')),
            ],
            options={
                'verbose_name': 'Рейтинг анкеты',
                'verbose_name_plural': 'Рейтинги анкет',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
        migrations.AddIndex(
            model_name='questionnairerating',
            index=models.Index(fields=['role', 'questionnaire_id', 'status'], name='ratings_que_role_8bf0af_idx'),
        ),
        migrations.AddIndex(
            model_name='questionnairerating',
            index=models.Index(fields=['reviewer', 'role', 'questionnaire_id'], name='ratings_que_reviewe_61a86b_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionnairerating',
            constraint=models.UniqueConstraint(fields=('reviewer', 'role', 'questionnaire_id'), name='unique_rating_per_questionnaire'),
        ),
    ]
