from django.urls import path
from .views import (
    CheckPhoneView,
    VerifyLoginCodeView,
    LoginView,
    ForgotPasswordView,
    ResetPasswordView,
    ChangePasswordView,
    ChangePhoneNumberView,
    VerifyPhoneChangeView,
    AdminLoginView,
    UserProfileView,
    UserPublicProfileView,
    UserListView,
    QuestionnaireListView,
    QuestionnaireArchiveListView,
    DesignerQuestionnaireListView,
    DesignerQuestionnaireDetailView,
    DesignerQuestionnaireStatusUpdateView,
    DesignerQuestionnaireFilterChoicesView,
    RepairQuestionnaireListView,
    RepairQuestionnaireDetailView,
    RepairQuestionnaireStatusUpdateView,
    RepairQuestionnaireFilterChoicesView,
    SupplierQuestionnaireListView,
    SupplierQuestionnaireDetailView,
    SupplierQuestionnaireStatusUpdateView,
    SupplierQuestionnaireFilterChoicesView,
    MediaQuestionnaireListView,
    MediaQuestionnaireDetailView,
    MediaQuestionnaireStatusUpdateView,
    DesignerQuestionnaireModerationView,
    RepairQuestionnaireModerationView,
    SupplierQuestionnaireModerationView,
    MediaQuestionnaireModerationView,
    DesignerQuestionnaireArchiveView,
    DesignerQuestionnaireRestoreView,
    DesignerQuestionnaireDeleteView,
    RepairQuestionnaireArchiveView,
    RepairQuestionnaireRestoreView,
    RepairQuestionnaireDeleteView,
    SupplierQuestionnaireArchiveView,
    SupplierQuestionnaireRestoreView,
    SupplierQuestionnaireDeleteView,
    MediaQuestionnaireArchiveView,
    MediaQuestionnaireRestoreView,
    MediaQuestionnaireDeleteView,
    UserRolesView,
)

urlpatterns = [
    # Yangi autentifikatsiya
    path('login/check-phone/', CheckPhoneView.as_view(), name='check-phone'),
    path('login/verify-code/', VerifyLoginCodeView.as_view(), name='verify-login-code'),
    path('login/', LoginView.as_view(), name='login'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('change-phone/', ChangePhoneNumberView.as_view(), name='change-phone'),
    path('verify-phone-change/', VerifyPhoneChangeView.as_view(), name='verify-phone-change'),
    path('login-admin/', AdminLoginView.as_view(), name='admin-login'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('users/', UserListView.as_view(), name='user-list'),
    path('users/<int:id>/', UserPublicProfileView.as_view(), name='user-public-profile'),
    
    path('roles/', UserRolesView.as_view(), name='user-roles'),
    
    path('questionnaires/all/', QuestionnaireListView.as_view(), name='all-questionnaires-list'),
    path('questionnaires/all/archive/', QuestionnaireArchiveListView.as_view(), name='all-questionnaires-archive'),
    
    path('questionnaires/', DesignerQuestionnaireListView.as_view(), name='questionnaire-list'),
    path('questionnaires/filter-choices/', DesignerQuestionnaireFilterChoicesView.as_view(), name='questionnaire-filter-choices'),
    path('questionnaires/<int:pk>/', DesignerQuestionnaireDetailView.as_view(), name='questionnaire-detail'),
    path('questionnaires/<int:pk>/update-status/', DesignerQuestionnaireStatusUpdateView.as_view(), name='questionnaire-status-update'),
    path('questionnaires/<int:pk>/moderation/', DesignerQuestionnaireModerationView.as_view(), name='questionnaire-moderation'),
    path('questionnaires/<int:pk>/archive/', DesignerQuestionnaireArchiveView.as_view(), name='questionnaire-archive'),
    path('questionnaires/<int:pk>/restore/', DesignerQuestionnaireRestoreView.as_view(), name='questionnaire-restore'),
    path('questionnaires/<int:pk>/delete/', DesignerQuestionnaireDeleteView.as_view(), name='questionnaire-delete'),
    
    path('repair-questionnaires/', RepairQuestionnaireListView.as_view(), name='repair-questionnaire-list'),
    path('repair-questionnaires/filter-choices/', RepairQuestionnaireFilterChoicesView.as_view(), name='repair-questionnaire-filter-choices'),
    path('repair-questionnaires/<int:pk>/', RepairQuestionnaireDetailView.as_view(), name='repair-questionnaire-detail'),
    path('repair-questionnaires/<int:pk>/update-status/', RepairQuestionnaireStatusUpdateView.as_view(), name='repair-questionnaire-status-update'),
    path('repair-questionnaires/<int:pk>/moderation/', RepairQuestionnaireModerationView.as_view(), name='repair-questionnaire-moderation'),
    path('repair-questionnaires/<int:pk>/archive/', RepairQuestionnaireArchiveView.as_view(), name='repair-questionnaire-archive'),
    path('repair-questionnaires/<int:pk>/restore/', RepairQuestionnaireRestoreView.as_view(), name='repair-questionnaire-restore'),
    path('repair-questionnaires/<int:pk>/delete/', RepairQuestionnaireDeleteView.as_view(), name='repair-questionnaire-delete'),
    
    path('supplier-questionnaires/', SupplierQuestionnaireListView.as_view(), name='supplier-questionnaire-list'),
    path('supplier-questionnaires/filter-choices/', SupplierQuestionnaireFilterChoicesView.as_view(), name='supplier-questionnaire-filter-choices'),
    path('supplier-questionnaires/<int:pk>/', SupplierQuestionnaireDetailView.as_view(), name='supplier-questionnaire-detail'),
    path('supplier-questionnaires/<int:pk>/update-status/', SupplierQuestionnaireStatusUpdateView.as_view(), name='supplier-questionnaire-status-update'),
    path('supplier-questionnaires/<int:pk>/moderation/', SupplierQuestionnaireModerationView.as_view(), name='supplier-questionnaire-moderation'),
    path('supplier-questionnaires/<int:pk>/archive/', SupplierQuestionnaireArchiveView.as_view(), name='supplier-questionnaire-archive'),
    path('supplier-questionnaires/<int:pk>/restore/', SupplierQuestionnaireRestoreView.as_view(), name='supplier-questionnaire-restore'),
    path('supplier-questionnaires/<int:pk>/delete/', SupplierQuestionnaireDeleteView.as_view(), name='supplier-questionnaire-delete'),
    
    path('media-questionnaires/', MediaQuestionnaireListView.as_view(), name='media-questionnaire-list'),
    path('media-questionnaires/<int:pk>/', MediaQuestionnaireDetailView.as_view(), name='media-questionnaire-detail'),
    path('media-questionnaires/<int:pk>/update-status/', MediaQuestionnaireStatusUpdateView.as_view(), name='media-questionnaire-status-update'),
    path('media-questionnaires/<int:pk>/moderation/', MediaQuestionnaireModerationView.as_view(), name='media-questionnaire-moderation'),
    path('media-questionnaires/<int:pk>/archive/', MediaQuestionnaireArchiveView.as_view(), name='media-questionnaire-archive'),
    path('media-questionnaires/<int:pk>/restore/', MediaQuestionnaireRestoreView.as_view(), name='media-questionnaire-restore'),
    path('media-questionnaires/<int:pk>/delete/', MediaQuestionnaireDeleteView.as_view(), name='media-questionnaire-delete'),
] 